### ISSUE TITLE
Error namespace and backup-id

### ISSUE THREAD

**Issue by Gaetann18** [tizbac/proxmoxbackupclient_go#35] opened 2024-08-06 13:24 UTC
hello, I am pushing your script a little to save folders individually in snapshoot. Each employee having their own file, I want to be able to save each file independently under the same host.

For example : 
WS1/Gaetan
WS1/Arthur
...

This works a priori but as soon as I want to name the files using namespace or backup-id an error occurs, do you have any idea? 

Thanks in advance !

![image](https://github.com/user-attachments/assets/1ebb3f4c-1d80-442f-93cd-05a47d7eca43)

Currently my script only works as the name is not set correctly. And using your arguments it unfortunately doesn't work

---
I am attaching my script which works perfectly when you do not add backup-id / namespace

My Script : 
```
REM Dossiers à sauvegarder
set DIRS_TO_BACKUP=C:\Partages\gaetan C:\Partages\arthur

REM Paramètres communs de la commande de sauvegarde
set BASEURL=HIDE
set CERTFINGERPRINT=HIDE
set AUTHID=HIDE
set SECRET=HIDE
set DATASTORE=HIDE


REM Fichier de log
set LOGFILE=C:\save_bps_script\backup_log.txt

REM Nettoyer le fichier de log existant
if exist "%LOGFILE%" del "%LOGFILE%"

REM Boucle à travers les dossiers et exécuter la commande de sauvegarde
for %%D in (%DIRS_TO_BACKUP%) do (
    REM Extraire le nom du dossier pour le namespace
    set "DIRNAME=%%~nD"
    echo Sauvegarde de %%D avec namespace !DIRNAME!
    C:\save_bps_script\proxmoxbackupclient_go.exe -baseurl "%BASEURL%" -certfingerprint %CERTFINGERPRINT% -authid "%AUTHID%" -secret "%SECRET%" -backupdir "%%D" -datastore "%DATASTORE%"
    if errorlevel 1 (
        echo Erreur lors de la sauvegarde de %%D. Consultez le log pour plus de details. 
    )
    echo ---------------------------------------------------------------------- 
)

REM Attendre une interaction de l'utilisateur avant de fermer
echo Sauvegarde terminee. Appuyez sur une touche pour fermer ce script.
pause >nul

endlocal 
```

---

- If y try to use `namespace string` in command : `    C:\save_bps_script\proxmoxbackupclient_go.exe -baseurl "%BASEURL%" -certfingerprint %CERTFINGERPRINT% -authid "%AUTHID%" -secret "%SECRET%" -backupdir "%%D" -datastore "%DATASTORE%" -namespace "testnamespace"`

``` Starting backup of C:\Partages\Eleves
Creating VSS Snapshot...Snapshot created: {5260A765-C426-4FF4-9E10-4B1997D3EF20}
Symlink from:  \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy31\  to:  C:\Users\Administrateur\AppData\Roaming\PBSBackupGO\VSS\{5260A765-C426-4FF4-9E10-4B1997D3EF20}
Reading response to upgrade...
Unexpected response code: 404 Not Found
Error making request: Get "HIDE/previous?archive-name=backup.pxar.didx": Authentication error
Found leftover snapshot, deleting it...
panic: Get "HIDE/previous?archive-name=backup.pxar.didx": Authentication error

goroutine 1 [running, locked to thread]:
main.(*PBSClient).DownloadPreviousToBytes(0xc000130580, {0x7ff7a0ba14d9, 0x10})
        /home/runner/work/proxmoxbackupclient_go/proxmoxbackupclient_go/pbsapi.go:432 +0x525
main.main()
        /home/runner/work/proxmoxbackupclient_go/proxmoxbackupclient_go/main.go:119 +0x616
Erreur lors de la sauvegarde de C:\Partages\Eleves. Consultez le log pour plus de details.
----------------------------------------------------------------------

C:\save_bps_script>REM Attendre une interaction de l'utilisateur avant de fermer
```

If y try to use `Backup-id string`  in command : `    C:\save_bps_script\proxmoxbackupclient_go.exe -baseurl "%BASEURL%" -certfingerprint %CERTFINGERPRINT% -authid "%AUTHID%" -secret "%SECRET%" -backupdir "%%D" -datastore "%DATASTORE%" -backup-id "testbackupid"`
```
 flag provided but not defined: -backup-id
Usage of C:\save_bps_script\proxmoxbackupclient_go.exe:
  -authid string
        Authentication ID (PBS Api token)
  -backupdir string
        Backup source directory, must not be symlink
  -baseurl string
        Base URL for the proxmox backup server, example: https://192.168.1.10:8007
  -certfingerprint string
        Certificate fingerprint for SSL connection, example: ea:7d:06:f9...
  -datastore string
        Datastore name
  -namespace string
        Namespace (optional)
  -pxarout string
        Output PXAR archive for debug purposes (optional)
  -secret string
        Secret for authentication

```

**Comment by jochumdev** [comment] 2024-08-07 13:46
Hey @Gaetann18 

"backup-id" is not yet released, you have to build the binary on you'r own for that.

I recommend you to wait for patch #27 to be merged and use that for you'r use case.

**Comment by tizbac** [comment] 2024-11-21 01:01
Duplicate of #22

**Closed by tizbac** 2024-11-21 01:01 UTC
